name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

  build:
    name: Build Go binaries
    needs: release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            cgo: 1
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
            cgo: 0
          - os: windows-latest
            goos: windows
            goarch: amd64
            cgo: 1
          - os: macos-latest
            goos: darwin
            goarch: amd64
            cgo: 1
          - os: macos-latest
            goos: darwin
            goarch: arm64
            cgo: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies (Ubuntu)
        if: matrix.goos == 'linux' && matrix.cgo == 1
        run: |
          sudo apt-get update
          sudo apt-get install -y libopus-dev

      - name: Install dependencies (macOS)
        if: matrix.goos == 'darwin' && matrix.cgo == 1
        run: |
          brew install opus

      - name: Setup MSYS2 (Windows)
        if: matrix.goos == 'windows' && matrix.cgo == 1
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-opus
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-go
            zip

      - name: Build binary (Windows with MSYS2)
        if: matrix.goos == 'windows' && matrix.cgo == 1
        shell: msys2 {0}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: ${{ matrix.cgo }}
        run: |
          cd go-client
          export PATH="/mingw64/bin:$PATH"
          export PKG_CONFIG_PATH="/mingw64/lib/pkgconfig"
          output_name=trunecord-${{ matrix.goos }}-${{ matrix.goarch }}.exe
          mkdir -p dist
          go build -o dist/${output_name} ./cmd/
          
          # Package with DLLs
          ./scripts/package-windows.sh dist/${output_name} dist

      - name: Build binary (macOS)
        if: matrix.goos == 'darwin' && matrix.cgo == 1
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: ${{ matrix.cgo }}
        run: |
          cd go-client
          output_name=trunecord-${{ matrix.goos }}-${{ matrix.goarch }}
          mkdir -p dist
          go build -o dist/${output_name} ./cmd/
          
          # Package as macOS app
          ./scripts/package-macos.sh dist/${output_name} dist ${{ matrix.goarch }}

      - name: Build binary (other platforms)
        if: (matrix.goos != 'windows' && matrix.goos != 'darwin') || matrix.cgo != 1
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: ${{ matrix.cgo }}
        run: |
          cd go-client
          output_name=trunecord-${{ matrix.goos }}-${{ matrix.goarch }}
          if [ "${{ matrix.cgo }}" = "0" ]; then
            output_name="${output_name}-nocgo"
          fi
          if [ "${{ matrix.goos }}" = "windows" ]; then
            output_name="${output_name}.exe"
          fi
          go build -o dist/${output_name} ./cmd/

      - name: Upload Release Asset (Windows Package)
        if: matrix.goos == 'windows' && matrix.cgo == 1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./go-client/dist/trunecord-windows-amd64.zip
          asset_name: trunecord-windows-amd64.zip
          asset_content_type: application/zip

      - name: Upload Release Asset (macOS DMG)
        if: matrix.goos == 'darwin' && matrix.cgo == 1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./go-client/dist/trunecord-darwin-${{ matrix.goarch }}.dmg
          asset_name: trunecord-darwin-${{ matrix.goarch }}.dmg
          asset_content_type: application/x-apple-diskimage

      - name: Upload Release Asset (Other Platforms)
        if: matrix.goos != 'windows' && matrix.goos != 'darwin'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./go-client/dist/trunecord-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.cgo == 0 && '-nocgo' || '' }}
          asset_name: trunecord-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.cgo == 0 && '-nocgo' || '' }}
          asset_content_type: application/octet-stream